### ISSUE TITLE
Fonts don't update

### ISSUE THREAD

**Issue by VerzatileTom** [TVke/react-native-tailwindcss#14] opened 2020-02-04 07:25 UTC
I added a font following this guide: https://medium.com/@mehran.khan/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4

I tried to update my serif font in the tailwind config like this:
```js
fontFamily: {
  sans: 'Arial',
  serif: 'EBGaramond-Regular',
  mono: 'Courier New',
},
```
but it doesn't seem to work when I used it.

**Comment by TVke** [comment] 2020-02-04 12:10
Hey @VerzatileTom 

some questions for more details:
 - Have you tried changing the name? (maybe something is cached)
 - Is the font file correctly added in your project (iOS and Android)?
 - Have you tested both platforms? (as the naming is very different on each system)

Let me know if you checked these things 

In the docs there is a custom fonts section: (it's a small summary of the medium article) 
https://tvke.github.io/react-native-tailwindcss/typography/font-family.html#monospaced

Greetings
@TVke

**Comment by VerzatileTom** [comment] 2020-02-04 13:15
I managed to add the font by deleting the `tailwind.config.js` I copied from https://tvke.github.io/react-native-tailwindcss/installation.html because the `npx RNtailwindcss` command returns an error.

Then, I initialize the tailwind config again by running `tailwind init --full` then added my font like this
```
serif: [
  'EBGaramond-Regular',
  'Georgia',
  'Cambria',
  '"Times New Roman"',
  'Times',
  'serif',
],
```

**Comment by TVke** [comment] 2020-02-04 14:38
Hi @VerzatileTom 

Can I ask which kind of error did the command return? 
And now everything works as intended?

greetings
@TVke

**Comment by VerzatileTom** [comment] 2020-02-05 00:21
> Can I ask which kind of error did the command return?
```
cp: cannot stat '../react-native-tailwindcss/stubs/defaultConfig.stub.js': No such file or directory
```

> And now everything works as intended?
Yes, now works fine as expected.

**Comment by TVke** [comment] 2020-02-05 07:28
Hey @VerzatileTom 

What version of `react-native-tailwindcss` do you use?
as this error was fixed in [v1.1.9](https://github.com/TVke/react-native-tailwindcss/releases/tag/v1.1.9)

Hope this helps even more

Greetings
Thomas

**Comment by VerzatileTom** [comment] 2020-02-05 13:18
Hello @TVke,

I'm using v1.1.9.

**Comment by TVke** [comment] 2020-02-05 13:29
Hey @VerzatileTom 

Good to know I will research it more

**Closed by TVke** 2020-02-05 13:29 UTC
